name: Warlords
version: 1.3
description: >
  Recreation of warlords for the guild UnravelSoul

author: Niconator1
authors: [Hypixel]
website: www.hypixel.net
main: com.warlords.main.Warlords
load: STARTUP

commands:
    weapons:
        description: Opens the weapon inventory
    pyro:
        description: Chooses Pyromancer
    assassin:
        description: Chooses Assassine
    avenger:
        description: Chooses Avenger
    demon:
        description: Chooses Demon
    hunter:
        description: Chooses Hunter
    crusader:
        description: Chooses Crusader
    thunderlord:
        description: Chooses Thunderlord
    test:
        description: Chooses Testing Class
    ally:
        description: Adds/Removes/Lists allies
    togglemode:
        description: Toggle Abilitys
    toggleplayerattack:
        description: Toggles the attack of players
    removeclass:
        description: Removes the Class
    generateWeapon:
        description: Generates a weapon
    pontiff:
        description: Spawn Pontiff
permissions:
    warlords.*:
        default: false
        description: Alle Rechte.
        children:
            warlords.skill: true
            warlords.weapons: true
            warlords.choose: true
    warlords.skill:
        default: op
        description: Recht zum Nutzen von Faehigkeiten.
    warlords.weapons:
        default: op
        description: Recht zum Geben der Faehigkeiten.
    warlords.choose:
        default: op
        description: Recht zum auswaehlen der Klasse.
    warlords.cheat:
        default: op
        description: Recht zum Cheaten.
        